### ISSUE TITLE
Update Script for API v2?

### ISSUE THREAD

**Issue by simube** [f4bsch/DropPHP#18] opened 2017-01-05 12:15 UTC
Hi

Thanks for your great script!
When do you plan updating the functions for API v2? I need some functions, which do not yet work in your v2 script.
Otherwise I have to look for another class :(

**Comment by alsanan** [comment] 2017-02-17 10:51
+1
Deprecation date is on june 2017. After then, every script using DropPHP will stop working. Not nice.

**Comment by micha137** [comment] 2017-03-31 11:13
This is a duplicate of #15.

**Comment by f4bsch** [comment] 2017-10-15 06:50
DropPHP now supports v2

**Closed by f4bsch** 2017-10-15 06:50 UTC
